# Place this file in your FRONTEND project directory

services:
  - type: web
    name: front-end-qa
    env: static
    staticPublishPath: ./
    headers:
      - path: "/*.html"
        name: "Cache-Control"
        value: "no-store, no-cache, must-revalidate, private"
