# render.yaml for your FRONTEND static site

services:
  - type: web
    name: front-end-qa # You can name this whatever you like
    env: static
    staticPublishPath: ./ # Assumes your html files are in the root
    headers:
      - path: "/*.html" # Apply to all HTML pages
        name: "Cache-Control"
        value: "no-store, no-cache, must-revalidate, private"
      - path: "/*.html"
        name: "Pragma"
        value: "no-cache"
      - path: "/*.html"
        name: "Expires"
        value: "0"
